### ISSUE TITLE
给个macos的release，想尝试一下

### ISSUE THREAD

**Issue by UntaggedRui** [whiler/kmactor#6]
昨天刚想到这个场景，给别人展示我的一些东西，对方通过浏览器就能看到我的桌面。
于是在v站搜索了一下，没想到还真的被我找到了。
作者太强了，go语言真是个好东西。

如果自己有云服务的话，网页端可以自己搭建吗？
可以出个docker一键运行吗

**Comment by whiler** [comment]
没有 docker ，如果需要自己搭建网页端，可以看看这个仓库 https://github.com/whiler/noscreen 托管一个静态网页就可以了。

**Comment by whiler** [comment]
macos 的 release 在 https://noscr.v6.navy 和 https://github.com/whiler/kmactor/releases 都能找到

**Comment by UntaggedRui** [comment]
[noscreen中的config.json](https://github.com/whiler/noscreen/blob/master/config.json)
这个文件中的东西可以自己搭建吗

**Comment by whiler** [comment]
> [noscreen中的config.json](https://github.com/whiler/noscreen/blob/master/config.json) 这个文件中的东西可以自己搭建吗

可以的
actor 用  https://github.com/whiler/kmactor 搭建
signal 用 https://github.com/whiler/wspipe 搭建
turn 不是必须的，可以用 https://github.com/coturn/coturn 搭建

**Comment by whiler** [comment]
具体的搭建文档可以参考 https://github.com/whiler/noscreen/blob/master/deploy.md
